### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by AntonioSun** [ShenMian/sokoban-rs#6]
Hi, 

Thanks for providing this, the only none-python code available on GH. 

I'm not a rust programmer, how to build and run it (on Mac & Linux) pls? thx.

**Comment by ShenMian** [comment]
Precompiled Linux executables have just been uploaded to [Release v0.1.17](https://github.com/ShenMian/sokoban-rs/releases/tag/v0.1.17).

Compiling this project requires the Rust toolchain, which can be installed with the following command:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

Run the following command in the project root directory to compile and run the program:

```
cargo run --release
```

**Comment by AntonioSun** [comment]
Thanks!
